### ISSUE TITLE
uses deprecated API when building for Android

### ISSUE THREAD

**Issue by jweidner-mbible** [kaichii/pdf_viewer#10]
When building for Android, I get the warning: 

easy_pdf_viewer/EasyPdfViewerPlugin.java uses or overrides a deprecated API.

Running "flutter doctor" shows:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by jweidner-mbible** [comment]
after upgrading to Flutter 3.3.1 the issue went away.

**Comment by DenisMrGnusa** [comment]
me using flutter version 3.3.2 still got the error.

Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (11 days ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0

error like bellow:
`flutter/.pub-cache/hosted/pub.dartlang.org/easy_pdf_viewer-1.0.3/android/src/main/java/com/aboutkai/easy_pdf_viewer/EasyPdfViewerPlugin.java uses or overrides a deprecated API.`
