### ISSUE TITLE
setState being called wrong

### ISSUE THREAD

**Issue by wesleycrispy** [kaichii/pdf_viewer#13]
Hello , using your plugin i get this error sometimes, setState is being called wrong somehow and throws an error on my PDF page
can you please have a look.
       
at State.setState(framework.dart:1129)
       at _PDFPageState._repaint.<fn>(page.dart:57)

**Comment by kaichii** [comment]
Can you provide your usage? I'll check back later.

**Comment by Rafal-Okuniewski** [comment]
I think you should change this part:
```
  _repaint() {
    provider = FileImage(File(widget.imgPath!));
    final resolver = provider.resolve(createLocalImageConfiguration(context));
    resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
      if (!alreadyPainted) setState(() {});
    }));
  }
```
to
```
  void _repaint() {
    provider = FileImage(File(widget.imgPath!));
    final resolver = provider.resolve(createLocalImageConfiguration(context));
    resolver.addListener(
      ImageStreamListener(
        (imgInfo, alreadyPainted) {
          if (!alreadyPainted && mounted) setState(() {});
        },
      ),
    );
  }
```

**Comment by Rafal-Okuniewski** [comment]
btw. I have same issue

**Comment by kaichii** [comment]
> I think you should change this part:
> 
> ```
>   _repaint() {
>     provider = FileImage(File(widget.imgPath!));
>     final resolver = provider.resolve(createLocalImageConfiguration(context));
>     resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
>       if (!alreadyPainted) setState(() {});
>     }));
>   }
> ```
> 
> to
> 
> ```
>   void _repaint() {
>     provider = FileImage(File(widget.imgPath!));
>     final resolver = provider.resolve(createLocalImageConfiguration(context));
>     resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
>           if (!alreadyPainted && mounted) setState(() {});
>         },
>       ),
>     );
>   }
> ```
> 
> I mean add this flag **&& mounted**

Thanks! I'll try this.

**Comment by kaichii** [comment]
> I simply use the example as provided in the package description but sometimes this error gets called/

I don't find the error you said, what's your `flutter doctor -v` output?

**Comment by wesleycrispy** [comment]
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-AL)
    • Flutter version 3.3.8 on channel stable at /wesley
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5556 • android-arm64  • Android 9 (API 28) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

i changed all the path naming but obviously they are correct and working!

**Comment by kaichii** [comment]
> [✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-AL) • Flutter version 3.3.8 on channel stable at /wesley • Upstream repository [flutter/flutter.git](https://github.com/flutter/flutter.git) • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800 • Engine revision 857bd6b74c • Dart version 2.18.4 • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1) • Android SDK at /Users/user/Library/Android/sdk • Platform android-33, build-tools 32.1.0-rc1 • Java binary at: /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1) • Xcode at /Applications/Xcode.app/Contents/Developer • Build 14A400 • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 [plugins.jetbrains.com/plugin/9212-flutter](https://plugins.jetbrains.com/plugin/9212-flutter) • Dart plugin can be installed from: 🔨 [plugins.jetbrains.com/plugin/6351-dart](https://plugins.jetbrains.com/plugin/6351-dart) • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] Android Studio (version 2021.3) • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 [plugins.jetbrains.com/plugin/9212-flutter](https://plugins.jetbrains.com/plugin/9212-flutter) • Dart plugin can be installed from: 🔨 [plugins.jetbrains.com/plugin/6351-dart](https://plugins.jetbrains.com/plugin/6351-dart) • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
> 
> [✓] VS Code (version 1.73.1) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.52.0
> 
> [✓] Connected device (3 available) • Android SDK built for arm64 (mobile) • emulator-5556 • android-arm64 • Android 9 (API 28) (emulator) • macOS (desktop) • macos • darwin-arm64 • macOS 12.6 21G115 darwin-arm • Chrome (web) • chrome • web-javascript • Google Chrome 107.0.5304.110
> 
> [✓] HTTP Host Availability • All required HTTP hosts are available
> 
> i changed all the path naming but obviously they are correct and working!

Does the error disappear?

**Comment by kaichii** [comment]
> 



> I think you should change this part:
> 
> ```
>   _repaint() {
>     provider = FileImage(File(widget.imgPath!));
>     final resolver = provider.resolve(createLocalImageConfiguration(context));
>     resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
>       if (!alreadyPainted) setState(() {});
>     }));
>   }
> ```
> 
> to
> 
> ```
>   void _repaint() {
>     provider = FileImage(File(widget.imgPath!));
>     final resolver = provider.resolve(createLocalImageConfiguration(context));
>     resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
>           if (!alreadyPainted && mounted) setState(() {});
>         },
>       ),
>     );
>   }
> ```
> 
> I mean add this flag **&& mounted**

@Rafal-Okuniewski @wesleycrispy  Does that work? I still get no error. :< If it works, I'll update and publish.

**Comment by wesleycrispy** [comment]
@kaichii the mounted flag should work and is the correct way to setState with no errors from flutter. Its hard to replicate this tbh but that is exactly what is needed! thank you and best regards

**Comment by kaichii** [comment]
@wesleycrispy OK! I'll publish it later.
