### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by mtzinfotech** [kaichii/pdf_viewer#15]
update the numpicker version ^2.1.2

**Comment by mtzinfotech** [comment]
update the numpicker version ^2.1.2

**Comment by kaichii** [comment]
> update the numpicker version ^2.1.2

Why do you want this?

**Comment by kaichii** [comment]
@mtzinfotech Now [1.0.7](https://pub.dartlang.org/packages/easy_pdf_viewer) is released.

**Comment by mtzinfotech** [comment]
@kaichii Thank you for support.

**Comment by kaichii** [comment]
> @kaichii Thank you for support.

I'm glad to assist you. Please don't hesitate to bring up any concerns or problems you may have.
