### ISSUE TITLE
How can i change "Pick a number" text?

### ISSUE THREAD

**Issue by mesaglam** [kaichii/pdf_viewer#21]
Hi, first of all thank you very much for your great efforts to build that awesome package. I just wonder that can i change the text of the picker dialog?

Thanks...

**Comment by kaichii** [comment]
> Hi, first of all thank you very much for your great efforts to build that awesome package. I just wonder that can i change the text of the picker dialog?
> 
> Thanks...

Use [tooltip](https://github.com/kaichii/pdf_viewer/blob/main/lib/src/tooltip.dart#L14C33-L14C33:~:text=%3D-,%22Pick%20a%20page%22,-%2C)'s pick to change that
