### ISSUE TITLE
[android] PdfRenderer is not closed and memory leaks every time a document is opened.

### ISSUE THREAD

**Issue by acn-masatadakurihara** [kaichii/pdf_viewer#27]
Specifically [here.](https://github.com/kaichii/pdf_viewer/blob/main/android/src/main/java/dev/kaichi/easy_pdf_viewer/EasyPdfViewerPlugin.java#L131)
Since getNumberOfPages is executed each time a [file is opened](https://github.com/kaichii/pdf_viewer/blob/v1.0.7/lib/src/document.dart#L31C52-L31C68), the Renderer object is not released and stored.

**Comment by acn-masatadakurihara** [comment]
PR
https://github.com/kaichii/pdf_viewer/pull/28

**Comment by kaichii** [comment]
> PR. @kaichii Please confirm #28

Thx for your contribution!
