### ISSUE TITLE
uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by dryasbk** [kaichii/pdf_viewer#4]
Note: /Users/dryasbk/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/easy_pdf_viewer-1.0.0/android/src/main/java/pt/tribeiro/flutter_plugin_pdf_viewer/FlutterPluginPdfViewerPlugin.java uses or overrides a deprecated API.

**Comment by kaichii** [comment]
Links to the other [issue](https://github.com/kaichii/pdf_viewer/issues/5).
