### ISSUE TITLE
The following _CastError was thrown building NotificationListener<KeepAliveNotification>: Null check operator used on a null value

### ISSUE THREAD

**Issue by dryasbk** [kaichii/pdf_viewer#5]
======== Exception caught by widgets library =======================================================
![Screenshot_1628693121](https://user-images.githubusercontent.com/63132499/129229418-087846c5-cd57-4181-bbee-275e95ac7022.png)

The relevant error-causing widget was: 
  PDFViewer file:///Users/..../lib/views/pdf_screen.dart:210:15
When the exception was thrown, this was the stack: 
#0      _PDFPageState._repaint (package:easy_pdf_viewer/src/page.dart:54:45)
#1      _PDFPageState.didChangeDependencies (package:easy_pdf_viewer/src/page.dart:42:5)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4732:11)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
...
====================================================================================================

**Comment by kaichii** [comment]
Can you provide more details? such as flutter doctor -v、full example code.
